language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - pypy

env:
  - TEST_RELEASE=false

matrix:
  include:
  - env:
      TEST_RELEASE=true

install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - >
      if [[ "$TEST_RELEASE" == true ]]; then
        py.test test_release.py
      else
        if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
          py.test test/
        else
          py.test -n 4 --cov hyper test/
          coverage report -m --fail-under 100
        fi
      fi
